# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8FK-jSO4htVBhGXR_kujsqeZ16p08Cv
"""

lista = [ 4, 8, 10, 16, 18, 20, 24]
print(lista[0])
print(lista[1])
print(lista[2])
print(lista[3])
print(lista[4])
print(lista[5])
print(lista[6])

